[kotto]
name = "kotto"
description = "kotto - he wants to play a game"
thumbnail = "https://i.postimg.cc/1m0NVtjf/kotto-thumbnail.png"
download_link = "https://github.com/JovialGirls/kittylink/releases/download/kotto_v1/kotto.zip"
